# Generated by Django 4.1.1 on 2022-10-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag_alter_category_name_alter_category_sulg_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="tag", new_name="tags",),
    ]
