# Generated by Django 4.1.1 on 2022-10-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_sulg_category_slug"),
    ]

    operations = [
        migrations.RenameField(model_name="tag", old_name="sulg", new_name="slug",),
    ]
