# Generated by Django 4.1.1 on 2022-10-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_sulg_tag_slug"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="tags", new_name="tag",),
    ]
