# Generated by Django 4.1.1 on 2022-11-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.comment",
                verbose_name="コメント",
            ),
        ),
    ]
