# Generated by Django 4.1.1 on 2022-11-10 23:54

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_rename_post_reply_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(verbose_name="本文"),
        ),
    ]
